name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deployments
        uses: actions/github-script@v7
        id: set-result
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            result = await github.rest.repos.listDeployments({
              owner: 'octodemo', 
              repo: 'cd-poc-front', 
              environment: 'cd'
            })
            console.log(JSON.stringify(result.data[0]));    
            return result.data[0].payload
      - name: Show deployment id
        run: |
          echo "Result = ${{ steps.set-result.outputs.result }}"
          echo "Run = ${{ fromJSON(steps.set-result.outputs.result).run }}"
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.MY_PAT }}
          repository: 'octodemo/cd-poc-front'
          run-id: ${{ steps.set-result.outputs.result.run }}
      - name: Display structure of downloaded files
        run: ls -R
