name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Get the deployments
        uses: actions/github-script@v7
        id: set-result
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const query = `query($orgName:String!, $repo:String!) { 
              repository(owner:$orgName, name:$repo) { 
                deployments( environments:["qa"], first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {'orgName': 'octodemo', 'repo': 'cd-poc-front'}
            const result = await github.graphql(query, variables)
            console.log(result)

