name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deployments
        uses: actions/github-script@v7
        id: set-result
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const query = `query($orgName:String!, $repo:String!) { 
              repository(owner:$orgName, name:$repo) { 
                deployments( environments:["cd"], first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    payload
                  }
                }
              }
            }`;
            const variables = {'orgName': 'octodemo', 'repo': 'cd-poc-front'}
            const result = await github.graphql(query, variables)
            const jsonPayload = JSON.parse(result.repository.deployments.nodes[0].payload)
            console.log("RUN", jsonPayload.run)
            return jsonPayload
      - name: Show deployment id
        run: |
          echo "Result = ${{ steps.set-result.outputs.result }}"
          echo "Run = ${{ steps.set-result.outputs.result.run }}"
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.MY_PAT }}
          repository: 'octodemo/cd-poc-front'
          run-id: ${{ steps.set-result.outputs.result.run }}
      - name: Display structure of downloaded files
        run: ls -R
