name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deployments
        uses: actions/github-script@v7
        id: set-result
        with:
          github-token: ${{ secrets.MY_PAT }}
          result-encoding: string
          script: |
            const query = `query($orgName:String!, $repo:String!) { 
              repository(owner:$orgName, name:$repo) { 
                deployments( environments:["qa"], first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    databaseId
                  }
                }
              }
            }`;
            const variables = {'orgName': 'octodemo', 'repo': 'cd-poc-front'}
            const result = await github.graphql(query, variables)
            console.log(result.repository.deployments.nodes[0].databaseId)
            return result.repository.deployments.nodes[0].databaseId
      - name: Show deployment id
        run: echo "${{ steps.set-result.outputs.result }}"
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.MY_PAT }}
          repository: 'octodemo/cd-poc-front'
          run-id: ${{ steps.set-result.outputs.result }}
      - name: Display structure of downloaded files
        run: ls -R
