name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deployments
        uses: actions/github-script@v7
        id: set-result
        result-encoding: string
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const query = `query($orgName:String!, $repo:String!) { 
              repository(owner:$orgName, name:$repo) { 
                deployments( environments:["qa"], first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {'orgName': 'octodemo', 'repo': 'cd-poc-front'}
            const result = await github.graphql(query, variables)
            return result.repository.deployments.nodes[0]
      - name: Show deployment id
        run: echo "${{ steps.set-result.outputs.result }}"
